version: "3.7"
services:
  backend:
    build: ./backend
    ports:
      - "3335:3333"

  frontend:
    build: ./frontend
    ports:
      - "5002:80"
    environment:
      - REACT_APP_MAPBOX_TOKEN=${TOKEN}
